### ISSUE TITLE
TIGRE VENERDÌ 

### ISSUE THREAD

**Issue by zeidof** [BIOLorenz/Xiaomi.eu-MIUI_v14-Italian#1]
Buongiorno,
C'è ancora questo errore nel schermo blocca, cambiato ma ancora è sbagliato, il mio cellulare è Xiaomi 12.
![Screenshot_2023-02-03-21-26-17-160_lockscreen](https://user-images.githubusercontent.com/122131943/216705673-45b5e94a-60f5-4bc0-9b47-a40d99f72bff.jpg)

**Comment by faroscin72** [comment]
Same with 23.2.13 on a Mi 11 Ultra

![1677074096500](https://user-images.githubusercontent.com/126085817/220646168-da87d7b9-2ac6-475c-bff0-bdff5fceddc2.jpg)
