### ISSUE TITLE
Traduzioni Mancanti HyperOS 12.04

### ISSUE THREAD

**Issue by colmoschin94** [BIOLorenz/Xiaomi.eu-MIUI_v14-Italian#13]
Sperando di fare cosa gradita ho fatto un breve elenco delle traduzioni che ad oggi non sono riportate su HyperOS 12.4 su Cupid, affiancando un possibile suggerimento per la traduzione in italiano. Ciao!

Selezione Modalità silenziosa:
Dynamic Island: "Modalità Silenziosa Attivata" / "Modalità Silenziosa Disattivata".

Selezione DND:
Dynamic Island: "DND Attivato" / "DND Disattivato".

MiMail:
Due Caratteri in Cinese appaiono all'inizio della preview di alcune mail, Google translate suggerisce che significhino "immagine".

Mifiles>Impostazioni
"Don't show MiDrive Files in Recents">"Non Mostrare File MiDrive nei Recenti".
"Additional Services">"Servizi Aggiuntivi".

MiCalculator>Menù
"History">"Cronologia".

MiRecorder>Search bar
"Search All Recordings">"Cerca Registrazione"

Impostazioni>Il mio dispositivo
"Camera Specs">"Dettagli Fotocamera"

Impostazioni>Wifi
"Network Acceleration" > "Accelerazione Rete" (SubMenu completamente in Inglese)

Impostazioni>Interconnettivitá
SubMenu completamente in Inglese

Impostazioni>More Connectivity Options
"Opzioni Aggiuntive Connettività"

Impostazioni>Notifications and Status Bar
"Barra di stato e Notifiche"

Impostazioni>Display and Brightness
"Display e Luminosità"

Impostazioni>Fingerprints, FaceData and Screen Lock
"Schermata di Sblocco, Impronte e Sblocco Facciale"

**Comment by C4rdi** [comment]
![Screenshot_2023-12-14-14-51-39-251_com miui securitycenter](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/149917817/451b45dd-e38a-49cb-b9a1-bff338b8565e)
![Screenshot_2023-12-14-14-51-44-945_com miui securitycenter](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/149917817/a5fb2d1c-669d-49ab-a8d2-1bb2001d29bc)
![Screenshot_2023-12-14-14-55-51-481_com miui securitycenter](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/149917817/5c4ed877-f2e3-4708-9ef1-5b27b03142e7)
![Screenshot_2023-12-14-14-55-56-453_com miui securitycenter](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/149917817/4909bd11-bf00-4992-84a9-95278571320f)
![Screenshot_2023-12-14-14-57-41-980_com miui home](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/149917817/87bc603f-2770-458f-b7a7-5764aab6d567)
![Screenshot_2023-12-14-14-57-45-066_com miui home](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/149917817/8fd653ac-638a-48ff-ae4a-0352b6536703)
![Screenshot_2023-12-14-14-57-52-285_com miui home](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/149917817/85fc66b6-3deb-43f3-b5d8-ef23a7d53772)
![Screenshot_2023-12-14-14-58-52-369_com miui securitycenter](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/149917817/fd0e9659-0ff5-4838-af0e-74d3a71ca863)
![Screenshot_2023-12-14-14-58-57-698_com miui securitycenter](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/149917817/5ec663eb-50ae-410a-8c08-cb6f806cc703)
Salve, sempre per il dispositivo Cupid:

Gestisci applicazioni
"Search apps">"Ricerca app"

Gestisci applicazioni>Impostazioni
"System app settings">"Impostazioni app di sistema"

Widget meteo
Manca traduzione tempo atmosferico

Tocco prolungato su cartella home>edit folder
"Edit folder">"Modifica cartella"
"Size">"Grandezza"
"Regular">"Normale"
"Enlarged">""Ingrandita"

Menù applicazioni
"Group icons by color">"Raggruppa icone per colore"
"Group icons by color to find apps faster">"Raggruppa icone per colore per trovarle velocemente"
"Animation in color categories">"Animazione nelle categorie colore"

Su schermata blocco, il formato data è MM/GG invece di GG/MM

Allo scollegamento del dispositivo dalla rete Wi-Fi
"Wi-Fi is off">"Il Wi-fi è disattivato"
Al collegamento del dispositivo alla rete Wi-Fi
"Wi-Fi is on">"Il Wi-Fi è attivato"

Impostazioni app>nome dell'app
"Pause app activity if unused">"Metti in pausa l'attività app se inutilizzata"
"Remove permissions, delete temporary files, and stop notifications">"Rimuovi permessi, cancella file temporanei e blocca le notifiche"

Impostazioni app>nome dell'app>Permessi
"Phone">"Telefono"
"Location">"Posizione"
"Microphone">"Micorofono"
"Nearby devices">"Dispositivi Nearby"
"Other permissions">"Altri permessi"

Impostazioni app>App management
"Gestione app"

Impostazioni app>App management
"Block app downloads">"Blocca i download dall'app"
"Prevent this app from downloading or installing other apps">"Previeni il download o l'installazione di altre app"
"Block opening other apps">"Blocca l'apertura di altre app"
"Prevent this app from connecting to or opening other apps">"Preveni la connessione o l'apertura di altre app"


La richiesta di inserimento del codice PIN della SIM è in inglese
