### ISSUE TITLE
errors translate italian FUXI_V14.0.31.0.TMCCNXM_v14-13.zip

### ISSUE THREAD

**Issue by ivanbelli** [BIOLorenz/Xiaomi.eu-MIUI_v14-Italian#14]
![Screenshot_2024-01-02-14-16-34-275_com android camera-edit](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/a8cd60f6-8f12-40a3-a466-c5631545f249)
![Screenshot_2024-01-02-14-17-01-002_com android camera-edit](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/f6afa7cf-d37e-4abe-8d28-3b22273fb387)
![Screenshot_2024-01-02-14-18-22-075_com android camera-edit](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/0d1c7e4f-f758-4d5f-bbbd-265c20ce11f8)
![Screenshot_2024-01-02-12-51-21-184_com miui gallery](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/d3f4ac0f-588b-4082-9940-ecb8a00cc634)
![IMG_20240102_114604](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/d0c43da0-ce6a-4865-97a9-87657e517d67)
![IMG_20240102_114639](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/e645ca61-38df-4bd4-89f9-04370838eb89)
![IMG_20240102_114705](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/15c1f6d0-a9e3-4aae-8aca-189331ed9e3a)
![IMG_20240102_114725](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/30f9956f-ca22-45e4-b3f9-506716f70da9)
![IMG_20240102_114743](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/4eb7ad85-d865-4159-b581-c8d8b3113305)
![IMG_20240102_114842](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/27227bbb-2162-4b84-bc31-3bb738fd3b39)
![Screenshot_2024-01-02-11-51-03-022_com android thememanager-edit](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/9423db1d-bc27-499d-baee-10b2e56725af)
![Screenshot_2024-01-02-12-15-38-751_com android fileexplorer-edit](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/c35f08aa-7bd7-45d7-a779-2eeffac45a85)
![Screenshot_2024-01-02-12-16-18-891_com android fileexplorer-edit](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/9f398b01-4a5a-4df0-9575-74efd2a169d3)
![Screenshot_2024-01-02-12-16-33-547_com android fileexplorer-edit](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/a9e65b82-6004-4fe9-ae8e-3403558b3cca)
![Screenshot_2024-01-02-12-22-53-914_com milink service](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/155446034/adbac5ca-00cd-4dfb-93bd-f02b37f86d29)

**Comment by Hackintosh98** [comment]
Grazie per la segnalazione. proveremo a risolvere appena possibile

**Comment by Hackintosh98** [comment]
Chiudo poiché le versioni della MIUI14 probabilmente non verranno più aggiornate, poiché Xiaomi.eu probabilmente è concentrata con HyperOS
