### ISSUE TITLE
sfocatura sfondo tendina notifiche

### ISSUE THREAD

**Issue by ivanbelli** [BIOLorenz/Xiaomi.eu-MIUI_v14-Italian#16]
Quando la batteria scende sotto il 20% o quando riduco a picture in picture netflix e tiro giù la tendina delle notifiche lo sfondo non viene sfocato e si mescola con la tendina

**Comment by NextWork123** [comment]
Salve, sembra che tu abbia commesso un errore nel segnalare il problema, poiché la repository riguarda le traduzioni italiane di xiaomi eu.

**Comment by Hackintosh98** [comment]
Chiudo poiché non ha a che fare con le traduzioni
