### ISSUE TITLE
Dead translation?

### ISSUE THREAD

**Issue by NextWork123** [BIOLorenz/Xiaomi.eu-MIUI_v14-Italian#17]
Hello, I was wondering why the repository isn't being updated and why all the issues aren't being addressed? @ingbrzy @BIOLorenz

**Comment by Hackintosh98** [comment]
Ciao, la repository non viene aggiornata semplicemente perché gli sviluppatori si dedicano al progetto quando hanno del tempo da dedicare. 
Se vuoi partecipare alla traduzione guarda il file README.md per vedere chi contattare
