### ISSUE TITLE
Traduzioni mancanti HyperOS Stable 1.0.3 by xiaomi.eu

### ISSUE THREAD

**Issue by giusCB** [BIOLorenz/Xiaomi.eu-MIUI_v14-Italian#20]
allego screenshot su alcune schermate che ho trovato non ancora tradotte. Grazie per questo splendido lavoro !! 
![Screenshot_2024-04-01-17-14-29-551_com milink service](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/89214526/82a29df1-7e9d-479a-a503-357d9a83f569)
![Screenshot_2024-03-26-12-44-10-760_com android incallui](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/89214526/a620263d-378a-4d25-b98f-5f2cb725da43)
![Screenshot_2024-03-24-14-40-11-101_com miui packageinstaller](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/89214526/67f9ea8e-bb3a-4903-876a-d6a99de18e65)
![Screenshot_2024-03-31-21-43-54-582_com mi health](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/89214526/631fc722-6d4f-4ef7-8704-84cf4523a6e5)
![Screenshot_2024-04-01-17-05-25-855_com miui cleaner](https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian/assets/89214526/94a09837-d567-4deb-a6c6-30d5b74962f7)

**Comment by Hackintosh98** [comment]
Grazie per la segnalazione. proveremo a risolvere appena possibile
