### ISSUE TITLE
Mancano traduzioni

### ISSUE THREAD

**Issue by AlloMoseca41** [BIOLorenz/Xiaomi.eu-MIUI_v14-Italian#21]
Sono sulla versione OS1.0.4.0.ULLMIXM della xiaomi.eu per lo Xiaomi 13 Lite e ci sono traduzioni mancanti su mezzo/più di mezzo sistema. Mancano nelle impostazioni, nell'app telefono, nell'app sicurezza e molte molte altre app e sottoimpostazioni. Poi nella sezione id virtuale (per gli annunci) è in hindu (o altra lingua di quel territorio). Poi ci sono traduzioni che nella miui 14 c'erano e ora sono magicamente scomparse.
Sono delle mancanze che vanno dalla MIUI 13 ed è inaccettabile che siano mancanti dopo anni sulla HyperOS.

**Comment by Hackintosh98** [comment]
Grazie per la segnalazione.  I developers cercheranno di risolvere appena possibile. 
Tuttavia se vuoi partecipare alla traduzione, controlla il file README.md oppure puoi creare una tua repository e creare una pull request

**Comment by AlloMoseca41** [comment]
e come posso fare per trovare il README.md? e Poi cos'è una pull request

**Comment by Hackintosh98** [comment]
sta nella repository. La pull request è una funzione di Github
