### ISSUE TITLE
Bugs Xiaomi 14 pro

### ISSUE THREAD

**Issue by Killer-Bueno** [BIOLorenz/Xiaomi.eu-MIUI_v14-Italian#24]
I bought xiaomi 14 pro and installed stable hyperos.  I immediately noticed a noticeable battery drain and the device overheats a lot without any heavy applications running.

**Comment by Hackintosh98** [comment]
this is for MIUI14 and not HyperOS 
Also this repo is for translation/translation reports, not software bugs
