### ISSUE TITLE
weather widget error in lockscreen / errore widget meteo nel lockscreen

### ISSUE THREAD

**Issue by Alez99** [BIOLorenz/Xiaomi.eu-MIUI_v14-Italian#25]
**ITA:**
l'errore si presenta su Xioami 14 con versione stabili 10.0.42/45 e su tutte le versioni DEV. 

il widget del meteo nel lockscreen non sena la temperatura corrente ma solo un trattino. il problema si manifesta solo con la lingua italiana, se si imposta la lingua inglese il meteo torna a funzionare. 

**ENG:**
the error occurs on Xioami 14 with stable version 10.0.42/45 and on all DEV versions. 

the weather widget in the lockscreen does not show the current temperature but only a dash. the problem occurs only with the Italian language, if you set the English language the weather works again.

![lockscreen ENG](https://github.com/user-attachments/assets/e1ffe26c-c237-456c-bee1-f78b2820a75f)
![lockscreen ITA](https://github.com/user-attachments/assets/bccec866-ec98-4397-812f-f790c7a4cac5)

**Comment by Hackintosh98** [comment]
Il bug mi è stato segnalato anche da altri utenti e sto cercando di risolvere appena posso. Chiudo la discussione solo perché questa è una vecchia repo non più aggiornata/appartenente alla traduzione per la MIUI14.

Se ti va, puoi repostare questo bug nella nuova repository, così mi è più facile tenerne traccia.
Questo è il link
https://github.com/Hackintosh98/HyperOS-XML-1.0-Italian
